#zadanie 14
DELIMITER $$
CREATE TRIGGER zad14 BEFORE DELETE ON osoba FOR EACH ROW 
BEGIN
UPDATE zwierzak SET ID = (SELECT ID FROM osoba ORDER BY RAND() LIMIT 1) WHERE zwierzak.ID LIKE OLD.id;
DELETE FROM hobby WHERE hobby.osoba LIKE OLD.id;
END$$
DELIMITER ;