#zadanie 18

DELIMITER $$
DROP PROCEDURE IF EXISTS Zad18 $$
CREATE PROCEDURE Zad18()
 BEGIN
SELECT imiê AS imiê,
(EXTRACT(YEAR FROM(NOW())) -EXTRACT(YEAR FROM(dataUrodzenia))) AS wiek
FROM osoba
ORDER BY COUNT(imiê) DESC LIMIT 1;

  END$$
DELIMITER ;